// ─── Kind-truth render check ──────────────────────────────────────────────────
// Every piece of chapter PROSE (Eos's own sentences — not the user's quoted
// words) passes two layers before it can be stored or shown:
//
//   1. Deterministic scrubs (this file, always on): clinical labels, verdict
//      phrases, digit-counts of behavior, timestamps, percentages,
//      distress-framed-as-regression. These are hard rules — no model
//      involved, so they hold even if the LLM checker is down.
//   2. A Haiku verification pass (best-effort): catches softer violations —
//      verdict-shaped judgments, generic advice not traceable to the user's
//      words, negative observations with no agency attached.
//
// Failed sections get regenerated by the caller; sections that still fail
// fall back to safe templates or are dropped entirely.

import { logAiUsage } from "../ai.js";

export interface ProseSection {
  name: string;
  text: string;
}

export interface SectionVerdict {
  name: string;
  pass: boolean;
  reasons: string[];
}

// Layer 1 — deterministic. Applied to Eos prose only, never to user quotes.
const CLINICAL_RE =
  /\b(depress\w*|anxiet\w*|anxious|rumina\w*|trauma(?:tiz\w*|tic)?|disorder\w*|diagnos\w*|clinical\w*|patholog\w*|narcissis\w*|codependen\w*|attachment style|ocd|ptsd|bipolar|spiral(?:ing)?)\b/i;
const VERDICT_RE =
  /\byou(?:'re| are)\s+(stuck|failing|regressing|broken|behind|worse|not (?:over|past) (?:it|him|her|them))\b/i;
const YOU_ABSOLUTE_RE = /\byou (always|never)\b/i;
const COUNT_RE =
  /\b\d+\s*(times?|nights?|mornings?|evenings?|days?|weeks?|messages?|hours?|minutes?)\b/i;
const CLOCK_RE = /\b(at|after|before|past|around)\s+\d{1,2}(:\d{2})?\s*(am|pm)\b/i;
const PERCENT_RE = /\d+(\.\d+)?\s*(%|percent)/i;
const SCORE_RE = /\b\d+\s*(?:\/|out of)\s*\d+\b/i;
const REGRESSION_RE = /\b(back to square one|backslid\w*|relaps\w*|lost (?:all )?(?:your |the )?progress|undone all)\b/i;

export function deterministicViolations(text: string): string[] {
  const reasons: string[] = [];
  const t = text ?? "";
  if (CLINICAL_RE.test(t)) reasons.push("clinical/diagnostic label used as a verdict");
  if (VERDICT_RE.test(t)) reasons.push("verdict-shaped judgment about the person");
  if (YOU_ABSOLUTE_RE.test(t)) reasons.push('absolutist judgment ("you always/never")');
  if (COUNT_RE.test(t)) reasons.push("digit-count of user behavior");
  if (CLOCK_RE.test(t)) reasons.push("timestamp of user behavior");
  if (PERCENT_RE.test(t)) reasons.push("percentage");
  if (SCORE_RE.test(t)) reasons.push("score/ratio of user behavior");
  if (REGRESSION_RE.test(t)) reasons.push("distress framed as regression");
  return reasons;
}

// Layer 2 — Haiku rubric. Best-effort: on model/parse failure we fall back to
// deterministic-only rather than blocking every chapter on an LLM outage.
const RUBRIC = `You are a strict reviewer of an emotional companion's weekly "chapter" prose written to a vulnerable adult. For each numbered section, decide PASS or FAIL.

FAIL a section if it contains ANY of:
- clinical or diagnostic language used as a verdict about the person (depressed, anxious, rumination, trauma-response, attachment style, etc.)
- verdict-shaped judgments ("you're stuck", "you haven't moved on", "you keep sabotaging")
- counts or timestamps of the person's behavior ("nineteen times", "after 11pm", "5 out of 7 days") — spelled-out casual words like "once" or "twice" are fine
- generic self-help advice that is not anchored to something the person themselves said (banned: journaling/meditation/self-care boilerplate they never mentioned)
- a negative observation with no agency handed back to the person (naming something hard is fine ONLY if the sentence also gives them a choice, a door, or their own words as evidence they can move)
- distress framed as regression or lost progress
- shaming, scolding, or disappointment, however softly worded

PASS otherwise. Warmth, specificity, the person's own quoted words, gentle questions, and "still true" framings are all good.

Respond with ONLY valid JSON: {"verdicts":[{"name":"<section name>","pass":true|false,"reasons":["..."]}]}`;

type AnthropicClient = {
  messages: { create: (opts: Record<string, unknown>) => Promise<{ content: unknown; usage?: unknown }> };
};

export async function checkKindTruth(
  sections: ProseSection[],
  anthropic: AnthropicClient | null,
): Promise<SectionVerdict[]> {
  const verdicts = new Map<string, SectionVerdict>();

  // Layer 1 — always.
  for (const s of sections) {
    const reasons = deterministicViolations(s.text);
    verdicts.set(s.name, { name: s.name, pass: reasons.length === 0, reasons });
  }

  // Layer 2 — only sections that survived layer 1, only if we have a model.
  const surviving = sections.filter((s) => verdicts.get(s.name)?.pass && s.text.trim().length > 0);
  if (anthropic && surviving.length > 0) {
    try {
      const listing = surviving
        .map((s, i) => `${i + 1}. [${s.name}]\n${s.text}`)
        .join("\n\n");
      const response = await anthropic.messages.create({
        model: "claude-haiku-4-5",
        max_tokens: 800,
        temperature: 0,
        messages: [{ role: "user", content: `${RUBRIC}\n\nSections:\n\n${listing}` }],
      });
      logAiUsage("chapter_kind_truth", "claude-haiku-4-5", (response as { usage?: unknown }).usage);
      const blocks = (response as { content: Array<{ type: string; text?: string }> }).content;
      const raw = blocks?.find((b) => b.type === "text")?.text ?? "";
      const cleaned = raw.replace(/```(?:json)?\n?/g, "").trim();
      const parsed = JSON.parse(cleaned) as { verdicts?: Array<{ name?: string; pass?: boolean; reasons?: string[] }> };
      for (const v of parsed.verdicts ?? []) {
        if (!v?.name || !verdicts.has(v.name)) continue;
        if (v.pass === false) {
          const existing = verdicts.get(v.name)!;
          existing.pass = false;
          existing.reasons.push(...(Array.isArray(v.reasons) ? v.reasons.map(String).slice(0, 4) : ["failed kind-truth review"]));
        }
      }
    } catch {
      // Best-effort layer — deterministic scrubs above remain the hard floor.
    }
  }

  return sections.map((s) => verdicts.get(s.name)!);
}
